services:
  db:
    image: postgres:16
    container_name: pg-api
    environment:
      POSTGRES_DB: usuariosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/usuariosdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: 3600000
    ports:
      - "8080:8080"

volumes:
  pgdata: