spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0

spring.jpa.hibernate.ddl-auto=update

app.s3.bucket-name=${APP_S3_BUCKET_NAME}
app.s3.region=${APP_S3_REGION:us-east-2}